Repository Lightning-AI/litgpt, pull requests merged in 2023-07, with the labels that each got.

#253 Bitsandbytes 4-bit quantization support
  README.md
  chat/base.py
  generate/adapter.py
  generate/adapter_v2.py
  generate/base.py
  generate/full.py
  generate/lora.py
  lit_gpt/config.py
  lit_gpt/utils.py
  notebooks/falcon-inference.ipynb
  quantize/bnb.py
  quantize/gptq.py
  requirements.txt
  tutorials/inference.md
  tutorials/quantize.md
Labels: enhancement, quantization, generation

#274 Support LLaMA 2
  README.md
  chat/base.py
  lit_gpt/config.py
  scripts/convert_hf_checkpoint.py
  scripts/download.py
  tests/test_model.py
  tutorials/download_llama_2.md
Labels: checkpoints

#273 Convert Lit-GPT Falcon Format to Original Falcon Format
  .gitignore
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
  tutorials/convert_lit_models.md
Labels: checkpoints

#309 Convert Lit-GPT GPT-NeoX Model Format to Original GPT-NeoX Format
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
Labels: checkpoints

#319 Fix Note Admonition
  tutorials/finetune_lora.md
  tutorials/quantize.md
  tutorials/tpus.md
Labels: documentation

#326 Fix convert_lit_checkpoint bin file creation
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
Labels: checkpoints
