Repository Lightning-AI/litgpt, pull requests merged in 2023-09, with the labels that each got.

#472 Add CodeLlama configs
  README.md
  chat/base.py
  lit_gpt/config.py
  lit_gpt/model.py
  lit_gpt/speed_monitor.py
  scripts/prepare_dolly.py
  scripts/prepare_lima.py
  tests/test_model.py
  tutorials/download_code_llama.md
  xla/finetune/adapter.py
  xla/generate/adapter.py
  xla/utils.py
Labels: checkpoints

#504 Introduce `Config.from_json`
  chat/base.py
  eval/lm_eval_harness.py
  eval/lm_eval_harness_lora.py
  generate/adapter.py
  generate/adapter_v2.py
  generate/base.py
  generate/full.py
  generate/lora.py
  lit_gpt/config.py
  quantize/gptq.py
  scripts/convert_lit_checkpoint.py
  scripts/prepare_redpajama.py
  tests/test_config.py
  xla/generate/adapter.py
  xla/generate/base.py
Labels: enhancement

#516 Add evaluation task details to neurips_challenge_quickstart.md
  tutorials/neurips_challenge_quickstart.md
Labels: documentation

#515 Preparing custom datasets instructions
  tutorials/prepare_dataset.md
Labels: documentation

#503 Add falcon-180B checkpoint support
  lit_gpt/config.py
  scripts/convert_hf_checkpoint.py
  scripts/download.py
  tests/test_model.py
  tutorials/download_falcon.md
Labels: checkpoints

#495 Merge lora script
  scripts/merge_lora.py
  tests/test_merge_lora.py
  tutorials/finetune_lora.md
Labels: enhancement, fine-tuning

#507 Move KV cache management out of forward
  chat/base.py
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  generate/adapter.py
  generate/adapter_v2.py
  generate/base.py
  generate/full.py
  generate/lora.py
  lit_gpt/adapter.py
  lit_gpt/adapter_v2.py
  lit_gpt/lora.py
  lit_gpt/model.py
  tests/test_generate.py
  tests/test_model.py
  xla/finetune/adapter.py
  xla/generate/adapter.py
  xla/generate/base.py
Labels: enhancement

#521 Add config for llama-2-7b-32k
  lit_gpt/config.py
Labels: checkpoints

#543 Fix KV cache with AMP
  lit_gpt/model.py
  tests/test_model.py
Labels: bug

#462 Add script to prepare dataset from csv
  .github/azure-gpu-tests.yml
  .github/workflows/cpu-tests.yml
  requirements.txt
  scripts/prepare_csv.py
  tests/test_prepare_csv.py
  tutorials/prepare_dataset.md
Labels: enhancement, good first issue

#552 Read the default encoding configuration from the tokenizer
  finetune/lora.py
  lit_gpt/tokenizer.py
  tests/test_tokenizer.py
Labels: enhancement

#360 Check if the checkpoint path exists before lazy loading it
  lit_gpt/utils.py
  tests/test_utils.py
Labels: enhancement

#569 Add Phi 1.5 support
  .gitignore
  README.md
  chat/base.py
  lit_gpt/adapter.py
  lit_gpt/adapter_v2.py
  lit_gpt/config.py
  lit_gpt/lora.py
  lit_gpt/model.py
  scripts/convert_hf_checkpoint.py
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
  tests/test_gptq.py
  tests/test_model.py
  tutorials/download_phi15.md
Labels: enhancement, checkpoints

#573 Add LongForm dataset (better than Alpaca)
  scripts/prepare_longform.py
  tutorials/prepare_dataset.md
Labels: fine-tuning

#586 Clarifications around `max_seq_length`
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  scripts/prepare_longform.py
  tutorials/alpaca_length_histogram.png
  tutorials/neurips_challenge_quickstart.md
  tutorials/oom.md
  tutorials/prepare_dataset.md
  xla/finetune/adapter.py
Labels: enhancement
