Repository Lightning-AI/litgpt, pull requests merged in 2023-08, with the labels that each got.

#315 Convert Lit-GPT LLaMA Model Format to Original LLaMA Format
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
Labels: checkpoints

#364 Make all args required in `convert_lit_checkpoint`
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
Labels: conversion

#404 Improve FLOPs calculation for finetuning scripts
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
Labels: bug, fine-tuning

#413 Avoid in-place operations in LoRA forward
  lit_gpt/lora.py
  tests/test_lora.py
Labels: fine-tuning

#397 Add `convert_lit_checkpoint::check_conversion_supported`
  scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
Labels: checkpoints, conversion

#422 feat: add vicuna v1.5 to config
  lit_gpt/config.py
  tutorials/download_vicuna.md
Labels: checkpoints
