Repository Lightning-AI/litgpt, pull requests merged in 2024-03, with the labels that each got.

#984 Copy configs to new checkpoint dir
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  lit_gpt/utils.py
  pretrain/pretrain.py
  tests/test_adapter.py
  tests/test_adapter_v2.py
  tests/test_full.py
  tests/test_lora.py
  tests/test_pretrain.py
  tests/test_utils.py
Labels: enhancement

#1006 Make prompt styles configurable in data modules
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  generate/adapter.py
  generate/adapter_v2.py
  generate/base.py
  generate/full.py
  generate/lora.py
  lit_gpt/__init__.py
  lit_gpt/args.py
  lit_gpt/data/__init__.py
  lit_gpt/data/alpaca.py
  lit_gpt/data/base.py
  lit_gpt/data/deita.py
  lit_gpt/data/dolly.py
  lit_gpt/data/flan.py
  lit_gpt/data/json.py
  lit_gpt/data/lima.py
  lit_gpt/data/longform.py
  lit_gpt/prompts.py
  tests/conftest.py
  tests/data/test_alpaca.py
  tests/data/test_base.py
  tests/data/test_deita.py
  tests/data/test_dolly.py
  tests/data/test_json.py
  tests/data/test_longform.py
  tests/data/test_openwebtext.py
  tests/test_prompts.py
  xla/generate/adapter.py
Labels: enhancement

#1012 Save the hyperparameters to the checkpoint
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  lit_gpt/pretrain.py
  lit_gpt/utils.py
  tests/test_adapter.py
  tests/test_adapter_v2.py
  tests/test_full.py
  tests/test_lora.py
  tests/test_pretrain.py
  tests/test_utils.py
Labels: enhancement

#1005 Refactor model prompt templates
  chat/base.py
  lit_gpt/prompts.py
  tests/test_prompts.py
Labels: enhancement

#1025 Save and load prompt style automatically
  chat/base.py
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  generate/adapter.py
  generate/adapter_v2.py
  generate/base.py
  generate/full.py
  generate/lora.py
  lit_gpt/prompts.py
  tests/test_adapter.py
  tests/test_adapter_v2.py
  tests/test_full.py
  tests/test_lora.py
  tests/test_prompts.py
Labels: enhancement

#1010 Update finetuning scripts
  config_hub/finetune/llama-2-7b/full.yaml
  config_hub/finetune/llama-2-7b/lora.yaml
  config_hub/finetune/tiny-llama/lora.yaml
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  generate/full.py
  lit_gpt/pretrain.py
  tests/test_adapter.py
  tests/test_adapter_v2.py
  tests/test_lora.py
Labels: bug, enhancement

#1027 Add alpaca 2k
  lit_gpt/data/__init__.py
  lit_gpt/data/alpaca_2k.py
  tutorials/images/prepare_dataset/alpaca-2k.jpg
  tutorials/prepare_dataset.md
Labels: enhancement

#1030 Updates to pretraining script
  config_hub/pretrain/tinyllama.yaml
  finetune/adapter.py
  finetune/adapter_v2.py
  finetune/full.py
  finetune/lora.py
  lit_gpt/pretrain.py
  lit_gpt/utils.py
  requirements-all.txt
  requirements.txt
  scripts/convert_hf_checkpoint.py
  scripts/convert_pretrained_checkpoint.py
  setup.py
  tests/test_convert_pretrained_checkpoint.py
  tests/test_pretrain.py
  tutorials/pretrain_tinyllama.md
Labels: enhancement

#1022 Hassle-free merging of LoRA weights
  finetune/lora.py
  generate/lora.py
  lit_gpt/lora.py
  scripts/merge_lora.py
  tests/test_generate_lora.py
  tests/test_lora.py
  tests/test_merge_lora.py
  tutorials/convert_lit_models.md
  tutorials/finetune_lora.md
Labels: enhancement

#1056 Remove config_path from convert_lit_checkpoint.py
  litgpt/scripts/convert_lit_checkpoint.py
  tests/test_convert_lit_checkpoint.py
  tutorials/convert_lit_models.md
Labels: enhancement

#1054 Enable loading train and val split in JSON data module
  litgpt/data/json.py
  tests/data/test_json.py
  tutorials/prepare_dataset.md
Labels: enhancement

#1063 Make logger configurable
  litgpt/finetune/full.py
  litgpt/finetune/lora.py
  litgpt/pretrain.py
  litgpt/utils.py
  tests/test_full.py
  tests/test_lora.py
  tests/test_pretrain.py
  tests/test_utils.py
  tutorials/pretrain_tinyllama.md
Labels: enhancement

#1078 Add support for loading JSONL
  litgpt/data/json.py
  tests/data/test_json.py
Labels: enhancement

#1081 Merge the final LoRA finetuned checkpoint
  litgpt/chat/base.py
  litgpt/finetune/lora.py
  litgpt/scripts/merge_lora.py
  tests/test_lora.py
  tutorials/finetune_lora.md
Labels: enhancement

#1162 Fix weight initialization for single device pretraining
  litgpt/pretrain.py
  litgpt/utils.py
  tests/test_pretrain.py
Labels: bug
