Repository Lightning-AI/litgpt, pull requests merged in 2024-02, with the labels that each got.

#928 Sort table alphabetically by model name
  README.md
Labels: documentation

#941 Add Gemma checkpoint support
  .github/azure-gpu-test.yml
  .github/workflows/cpu-tests.yml
  README.md
  chat/base.py
  lit_gpt/adapter_v2.py
  lit_gpt/config.py
  lit_gpt/lora.py
  lit_gpt/model.py
  lit_gpt/rmsnorm.py
  scripts/convert_hf_checkpoint.py
  scripts/convert_lit_checkpoint.py
  tests/test_config.py
  tests/test_convert_hf_checkpoint.py
  tests/test_convert_lit_checkpoint.py
  tests/test_generate_adapter.py
  tests/test_generate_lora.py
  tests/test_model.py
  tutorials/download_function_calling_llama_2.md
  tutorials/download_gemma.md
  tutorials/inference.md
Labels: checkpoints

#958 (1/n) Data Refactor - TinyLlama Pretraining
  .gitignore
  lit_gpt/data/__init__.py
  lit_gpt/data/data_module.py
  lit_gpt/data/tinyllama.py
  pretrain/tinyllama.py
  tests/data/__init__.py
  tests/data/test_tinyllama.py
  tests/test_pretrain_tinyllama.py
  tutorials/pretrain_tinyllama.md
Labels: enhancement

#972 Add Stable-Code-3B tutorial
  README.md
  lit_gpt/config.py
  tutorials/download_stablecode.md
Labels: checkpoints

#965 Download config.json for conversion script
  scripts/download.py
  tutorials/convert_lit_models.md
Labels: enhancement
