Repository Lightning-AI/litgpt, pull requests merged in 2024-05, with the labels that each got.

#770 LoRA: `zero_pad` speed improvements
  litgpt/lora.py
  tests/test_lora.py
Labels: performance

#1409 OptimizerArgs
  config_hub/finetune/falcon-7b/lora.yaml
  config_hub/finetune/falcon-7b/qlora.yaml
  config_hub/finetune/gemma-2b/full.yaml
  config_hub/finetune/gemma-2b/lora.yaml
  config_hub/finetune/gemma-2b/qlora.yaml
  config_hub/finetune/gemma-7b/lora.yaml
  config_hub/finetune/gemma-7b/qlora.yaml
  config_hub/finetune/llama-2-7b/full.yaml
  config_hub/finetune/llama-2-7b/lora.yaml
  config_hub/finetune/llama-2-7b/qlora.yaml
  config_hub/finetune/llama-3-8b/full.yaml
  config_hub/finetune/llama-3-8b/lora.yaml
  config_hub/finetune/llama-3-8b/qlora.yaml
  config_hub/finetune/mistral-7b-v0.2/lora.yaml
  config_hub/finetune/mistral-7b-v0.2/qlora.yaml
  config_hub/finetune/mistral-7b/lora.yaml
  config_hub/finetune/mistral-7b/qlora.yaml
  config_hub/finetune/phi-2/full.yaml
  config_hub/finetune/phi-2/lora.yaml
  config_hub/finetune/phi-2/qlora.yaml
  config_hub/finetune/stablelm-base-alpha-3b/full.yaml
  config_hub/finetune/stablelm-base-alpha-3b/lora.yaml
  config_hub/finetune/stablelm-base-alpha-3b/qlora.yaml
  config_hub/finetune/tiny-llama/full.yaml
  config_hub/finetune/tiny-llama/lora.yaml
  config_hub/finetune/tiny-llama/qlora.yaml
  config_hub/pretrain/debug.yaml
  config_hub/pretrain/tinyllama.yaml
  config_hub/pretrain/tinystories.yaml
  extensions/thunder/pretrain.py
  litgpt/__main__.py
  litgpt/args.py
  litgpt/finetune/adapter.py
  litgpt/finetune/adapter_v2.py
  litgpt/finetune/full.py
  litgpt/finetune/lora.py
  litgpt/pretrain.py
  litgpt/utils.py
  tests/test_config_hub.py
  tests/test_thunder_pretrain.py
  tests/test_utils.py
  tutorials/pretrain.md
Labels: breaking change

#1437 New CLI
  .gitignore
  README.md
  config_hub/pretrain/tinystories.yaml
  litgpt/__main__.py
  litgpt/chat/base.py
  litgpt/config.py
  litgpt/deploy/serve.py
  litgpt/eval/evaluate.py
  litgpt/finetune/adapter.py
  litgpt/finetune/adapter_v2.py
  litgpt/finetune/full.py
  litgpt/finetune/lora.py
  litgpt/generate/adapter.py
  litgpt/generate/adapter_v2.py
  litgpt/generate/base.py
  litgpt/generate/full.py
  litgpt/generate/sequentially.py
  litgpt/generate/tp.py
  litgpt/pretrain.py
  litgpt/scripts/convert_hf_checkpoint.py
  litgpt/scripts/convert_pretrained_checkpoint.py
  litgpt/scripts/download.py
  litgpt/scripts/merge_lora.py
  litgpt/utils.py
  tests/test_adapter.py
  tests/test_adapter_v2.py
  tests/test_chat.py
  tests/test_cli.py
  tests/test_config.py
  tests/test_config_hub.py
  tests/test_evaluate.py
  tests/test_full.py
  tests/test_generate.py
  tests/test_generate_adapter.py
  tests/test_generate_sequentially.py
  tests/test_generate_tp.py
  tests/test_lora.py
  tests/test_pretrain.py
  tests/test_readme.py
  tests/test_utils.py
  tutorials/0_to_litgpt.md
  tutorials/convert_hf_checkpoint.md
  tutorials/convert_lit_models.md
  tutorials/deploy.md
  tutorials/download_model_weights.md
  tutorials/evaluation.md
  tutorials/finetune.md
  tutorials/finetune_adapter.md
  tutorials/finetune_full.md
  tutorials/finetune_lora.md
  tutorials/inference.md
  tutorials/prepare_dataset.md
  tutorials/pretrain.md
  tutorials/pretrain_tinyllama.md
  tutorials/quantize.md
Labels: enhancement, breaking change
