Repository Lightning-AI/litgpt, pull requests merged in 2024-01, with the labels that each got.

#854 Refactor `get_lr` in pretraining scripts
  pretrain/openwebtext.py
  pretrain/openwebtext_trainer.py
  pretrain/redpajama.py
  pretrain/tinyllama.py
Labels: pre-training

#877 upgrade TinyLlama to latest checkpoints
  lit_gpt/config.py
  tests/test_config.py
  tutorials/download_tinyllama.md
Labels: checkpoints

#694 Support quantization with adapter v1 and v2 finetuning
  finetune/adapter.py
  finetune/adapter_v2.py
  tests/test_adapter.py
  tests/test_adapter_v2.py
  tests/test_lora.py
  tutorials/finetune_adapter.md
  tutorials/resource-tables.md
Labels: quantization
